### ISSUE TITLE
Milieu and worldbuilding epic

### ISSUE THREAD

**Issue by zkovari** [plotlyst/plotlyst-app#1309]
- [ ] **fantasy elements**
- [ ] milieu/locations panel
  - [ ] tree view
  - [ ] locations
    - [ ] summary
    - [ ] image
    - [ ] map location
    - [ ] linked article
    - [ ] present characters (from scenes)
    - [ ] dynamic fields: temperature, danger
  - [ ] societies
    - [ ] dynamic fields: leadership, motto, values, members
- [ ] timeline
  - [ ] different views
    - [ ] global
    - [ ] per article/location
- [ ] bible
  - [ ] offer topics as articles
  - [ ] save quote source
  - [ ] side commands for text
  - [ ] header margins
  - [ ] headers in highlghted text
  - [ ] dnd on the side
  - [ ] optional banner
  - [ ] "card" article
- [ ] map
- [ ] glossary
  - [ ] prepare domain for collections, new columns, custom labels
- [ ] themes and settings
  - [ ] different themes
  - [ ] optional banner
  - [ ] change colors
  - [ ] change bg image
  - [ ] change banner image
  - [ ] automatic link of known names
- [ ] cross-references
  - [ ] highlight glossary items in bible
  - [ ] link locations, elements, characters, societies
  - [ ] link locations to map markers
