### ISSUE TITLE
Hide storylines tracking if needed

### ISSUE THREAD

**Issue by zkovari** [plotlyst/plotlyst-app#776]
- [x] storymap toggle
- [x] plot association widget
- [x] plot widget per events
- [ ] nodes in report
